# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', jsonfield.fields.JSONField(verbose_name='Game state')),
                ('evt_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('evt_changed', models.DateTimeField(auto_now=True, verbose_name='Time of last change')),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', jsonfield.fields.JSONField(verbose_name='Game state')),
                ('score_of_blue_player', models.BigIntegerField(null=True, verbose_name='Score of blue player')),
                ('score_of_green_player', models.BigIntegerField(null=True, verbose_name='Score of green player')),
                ('score_of_red_player', models.BigIntegerField(null=True, verbose_name='Score of red player')),
                ('score_of_yellow_player', models.BigIntegerField(null=True, verbose_name='Score of yellow player')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_logs', to='laby.Game', verbose_name='Game of Log')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('current_color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow')], max_length=250, null=True, verbose_name='Current color')),
                ('current_score', models.BigIntegerField(null=True, verbose_name='Score')),
                ('game_history', models.ManyToManyField(related_name='players', to='laby.Game', verbose_name='Game history')),
                ('most_recent_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_players', to='laby.Game', verbose_name='Most recent game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='blue_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_of_blue_player', to='laby.Player', verbose_name='Blue player'),
        ),
        migrations.AddField(
            model_name='game',
            name='green_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_of_green_player', to='laby.Player', verbose_name='Green player'),
        ),
        migrations.AddField(
            model_name='game',
            name='red_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_of_red_player', to='laby.Player', verbose_name='Red player'),
        ),
        migrations.AddField(
            model_name='game',
            name='yellow_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_of_yellow_player', to='laby.Player', verbose_name='Yellow player'),
        ),
    ]
